In [21]:
# Import Numpy library
import numpy as np

In [22]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [23]:
print(a[0])     # first element of array

1


In [24]:
print(a[4])     # fifth element of array

9


In [25]:

print(a[-1])      # last element of array

9


In [26]:
a = np.array([1,3,5,7,9])
print(a)
# Slicing :
# array[start:stop:step]
# stop - index, that is not included in output

[1 3 5 7 9]


In [27]:
print(a[0:3]) # First 3 elements

[1 3 5]


In [28]:

print(a[-3:]) # Last 3 elements

[5 7 9]


In [29]:

print(a[1:4]) # Middle 3 elements

[3 5 7]


In [30]:
print(a[0::3]) # Middle 3 elements with steps

[1 7]


In [31]:
print(a[0::2]) # All alternative elements with steps

[1 5 9]


In [32]:
# Indexing on 2 Dimensional Array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

# 2D Array: [rows, columns]                   # 2D Array takes 2 values - rows and columns for indexing
# 3D Array: [layers/height, rows, columns]    # 3D Array takes 3 values - height, rows and columns for indexing

[[1 2 3]
 [4 5 6]]


In [33]:
print(arr2[0]) # first row
print(arr2[1]) # second row

[1 2 3]
[4 5 6]


In [15]:
# Slicing on 2D array
print(arr2[0][0]) # element of first row and first column
print(arr2[0][1]) # element of first row and second column
print(arr2[1][2]) # element of second row and third column

1
2
6


In [16]:
print(arr2[1]) # specific element - 1D
print(arr2[1:]) # slicing part - 2D

[4 5 6]
[[4 5 6]]


In [17]:
print(arr2)
# 2D Array: [rows, columns]  |  eg: arr2[0][1]     # 2D Array takes 2 values - rows and columns for indexing

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr2[1:])
print(arr2[:])

[[1 2 3]
 [4 5 6]]


In [40]:
print(arr2[:, 0])       # First column of an array
print(arr2[:, 1])       # Second column of an array
print(arr2[:, 2])       # Third column of an array
# 2d:[row,col]
# : → Sabhi rows select karo
# 0 → First column select karo

[3 6]


In [41]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)
print(arr3.ndim)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [19]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [20]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [21]:
print(arr3[:, 0]) # 1st col value
print(arr3[:, 1]) # 2nd col value
print(arr3[:, 2]) # 3rd col value

[1 4 7]
[2 5 8]
[3 6 9]


In [51]:
# print(arr3[::, 1:2])  #slicing on columns
print(arr3[2:]) #slicing on rows and columns

[[7 8 9]]
