In [1]:
# Import Numpy library
import numpy as np

In [2]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [3]:
# Attributes of Array (properties of array)
print("Shape", arr1.shape)  # share= rows, columns and height of array
print("Size", arr1.size)    # number of elements in array
print("dType", arr1.dtype)  # data type of elements in array
print("n_dim", arr1.ndim)   # dimension of array

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [4]:
# Shape (2, 3)  (y,x)

In [5]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr1)

print("\n1D Array Attributes:")
print("Shape:", arr1.shape)
print("Dimensions (ndim):", arr1.ndim)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)
print("Item Size:", arr1.itemsize)


# 3D Array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print("\n3D Array:")
print(arr3)

print("\n3D Array Attributes:")
print("Shape:", arr3.shape)
print("Dimensions (ndim):", arr3.ndim)
print("Size:", arr3.size)
print("Data Type:", arr3.dtype)
print("Item Size:", arr3.itemsize)

1D Array:
[10 20 30 40 50]

1D Array Attributes:
Shape: (5,)
Dimensions (ndim): 1
Size: 5
Data Type: int64
Item Size: 8

3D Array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

3D Array Attributes:
Shape: (3, 2, 2)
Dimensions (ndim): 3
Size: 12
Data Type: int64
Item Size: 8


In [6]:
# itemsize = datatype size in bytes

# int64 → 8 bytes
# int32 → 4 bytes
# float64 → 8 bytes

In [7]:
# Array initialization methods

In [8]:
# zeros array : all elements are 0

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# ones array : all elements are 1

one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Full array : all elements are same based on given value

full_arr = np.full((3,2), 7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [15]:
# Identity Matrix : diagonal elements are ones and all other elements are zeros

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# empty array
print(np.empty(0))

[]


In [15]:
# evenly spaced array : elements are evenly spaced based on step value
print(np.arange(1,3,1)) #1 add
print(np.arange(1,10,2)) #2 add

[1 2]
[1 3 5 7 9]


In [18]:
# specific number of eqaully spaced values between a range : elements are equally spaced based on step value
print(np.linspace(1,10,4)) #3 gap eqaully spaced

[ 1.  4.  7. 10.]


In [19]:
# random values array - float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.59545137 0.31610005]
 [0.57855419 0.79546974]
 [0.41592184 0.63306747]]


In [20]:
# random values array - int
rint_arr = np.random.randint(1,100,(3,3))   #(3,3) #shap
print(rint_arr)

[[63 44 77]
 [65  3 91]
 [76 45 60]]
