In [1]:
# Import Numpy library
import numpy as np

In [2]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [3]:
print(a[0])     # first element of array

1


In [4]:
print(a[2])     # first element of array

5


In [5]:
print(a[-1])      # last element of array

9


In [6]:
a = np.array([1,3,5,7,9])
print(a)
# Slicing :
# array[start:stop:step]
# stop - index, that is not included in output

[1 3 5 7 9]


In [7]:
print(a[0:3]) # First 3 elements

[1 3 5]


In [8]:
print(a[-3:]) # Last 3 elements

[5 7 9]


In [9]:
print(a[0::3]) # Middle 3 elements with steps

[1 7]


In [10]:
print(a[0::2]) # All alternative elements with steps

[1 5 9]


In [11]:
# Indexing on 2 Dimensional Array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

# 2D Array: [rows, columns]                
#2D Array takes 2 values - rows and columns for indexing


[[1 2 3]
 [4 5 6]]


In [12]:
print(arr2[0]) # first row
# print(arr2[1]) # second row

[1 2 3]


In [13]:
print(arr2[1]) # second row

[4 5 6]


In [14]:
print(arr2[0][2]) 

3


In [15]:
print(arr2[1][2]) 

6


In [16]:
print(arr2[1]) # specific element - 1D


[4 5 6]


In [17]:
print(arr2[1:]) # slicing part - 2D

[[4 5 6]]
