In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.4.4


In [5]:
#create array

In [6]:
list1 =[1,2,3]
print(list1)

[1, 2, 3]


In [7]:
arr_list1 =np.array(list1)
print(arr_list1)  #array one d

[1 2 3]


In [8]:
print(type(arr_list1))  #n-dimensional array (multi-dimensional array)

<class 'numpy.ndarray'>


In [12]:
list1 =[1,2,3]
list2 =[4,5,6]
arr_list1_2 =np.array([list1,list2])
print(arr_list1_2)  #2d array axio

[[1 2 3]
 [4 5 6]]


In [11]:
# # axis 0 → Rows (ऊपर से नीचे)
# # axis 1 → Columns (बाएँ से दाएँ)
# 2 Rows
# 3 Columns
# arr[0][0] = 1
# arr[1][2] = 6
# पहला index = Row
# दूसरा index = Column

In [14]:
list1 =[1,2,3]
list2 =[4,5,6]
list3 =[7,8,9]
arr_list1_3 =np.array([[list1,list2,list3]])
print(arr_list1_3)  #2d array axio

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
 print(arr_list1_3.ndim)

3
