In [8]:
# Import Numpy library
import numpy as np

In [9]:
# Reshape Array :Array ke data ko same rakhte hue uska structure change karna.
# Flatten Array:2D ya 3D array ko ek single line (1D) me convert karna.

In [10]:
arr1 = np.array([1,2,3,4,5,6])      # shape = (1,6) - 1 row and 6 columns
print(arr1)

[1 2 3 4 5 6]


In [14]:
reshaped = arr1.reshape((6,1))      # shape = (6,1) - 6 rows and 1 column
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:
reshaped2 = arr1.reshape((2,3))     # re-shaped array from (1,6) to (2,3)
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [18]:
# Flatten Array:2D ya 3D array ko ek single line (1D) me convert karna.

In [19]:
print(reshaped2.flatten()) # flattened array from higher (2D) dimensional (2,3) to (1,6) (1D)

[1 2 3 4 5 6]


In [ ]:
# 6 Array Stacking and Splitting